# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stamp < Formula
  desc "A beautiful CLI for managing Architecture Decision Records (ADRs)"
  homepage "https://github.com/stef16robbe/stamp"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stef16robbe/stamp/releases/download/v0.4.0/stamp_darwin_amd64"
      sha256 "6f51d4662d3ac13cc19ab7f1ed42f7a3c1086fd251d49e4d8dcf1c4113bf40a9"

      def install
        bin.install Dir.glob("stamp*").first => "stamp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stef16robbe/stamp/releases/download/v0.4.0/stamp_darwin_arm64"
      sha256 "2251e216c4ef5980de5a7eaeed80ee3ee7bfb9d94c0b514687e183923cc489fa"

      def install
        bin.install Dir.glob("stamp*").first => "stamp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stef16robbe/stamp/releases/download/v0.4.0/stamp_linux_amd64"
      sha256 "255ccfa2b4d305486bbf1bb2f95f353fb7ed32619a0f734b0d194e54e8ceb6cd"
      def install
        bin.install Dir.glob("stamp*").first => "stamp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stef16robbe/stamp/releases/download/v0.4.0/stamp_linux_arm64"
      sha256 "0898021ed3a575522b77bb1890e499420b08b5fdf481c01f4462cd39d6783cad"
      def install
        bin.install Dir.glob("stamp*").first => "stamp"
      end
    end
  end

  test do
    system "#{bin}/stamp", "version"
  end
end
