# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stamp < Formula
  desc "A beautiful CLI for managing Architecture Decision Records (ADRs)"
  homepage "https://github.com/stef16robbe/stamp"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stef16robbe/stamp/releases/download/v0.3.1/stamp_darwin_amd64"
      sha256 "2d3c751285d4ec56487ad46ef150e39f3269c59d92e14e5760547cbcd2c34aa3"

      def install
        bin.install Dir.glob("stamp*").first => "stamp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stef16robbe/stamp/releases/download/v0.3.1/stamp_darwin_arm64"
      sha256 "a037db81e14cc707f91d55ebc777b683dddc03d8d90c95a06f99580523f05810"

      def install
        bin.install Dir.glob("stamp*").first => "stamp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stef16robbe/stamp/releases/download/v0.3.1/stamp_linux_amd64"
      sha256 "36abe043b87a8ed3dbb785e6703838d0353de33a333a978384c80872a6fff9d2"
      def install
        bin.install Dir.glob("stamp*").first => "stamp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stef16robbe/stamp/releases/download/v0.3.1/stamp_linux_arm64"
      sha256 "2e53432dfa2cec7cfd55c8afd1a192d5b5c494e4ab5e3f6068bce420a2defcae"
      def install
        bin.install Dir.glob("stamp*").first => "stamp"
      end
    end
  end

  test do
    system "#{bin}/stamp", "version"
  end
end
